[versions]
agp = "8.3.2"
kotlin = "1.8.10"
coreKtx = "1.13.1"
ktfmt = "0.17.0"
appcompat = "1.7.0"
material = "1.12.0"
composeBom = "2024.09.03"
composeActivity = "1.9.2"
composeViewModel = "2.8.6"
lifecycleRuntimeKtx = "2.8.6"
json = "20240303"
mockitoAndroid = "5.13.0"
gms = "4.4.2"
navigationCompose = "2.8.2"

# Testing Unit
junit = "4.13.2"
mockitoCore = "5.13.0"
mockitoInline = "3.12.4"
mockitoKotlin = "5.4.0"
mockk = "1.13.7"


# Firebase Libraries
firebaseAuth = "23.0.0"
firebaseAuthKtx = "23.0.0"
firebaseDatabaseKtx = "21.0.0"
firebaseFirestore = "25.1.0"
firebaseUiAuth = "8.0.0"

# Testing UI
espressoCore = "3.6.1"
junitVersion = "1.2.1"
kaspresso = "1.5.5"
mockkAgent = "1.13.7"
mockkAndroid = "1.13.7"
robolectric = "4.11.1"
sonar = "4.4.1.3373"
firebaseCommonKtx = "21.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
compose-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

kaspresso = { group = "com.kaspersky.android-components", name = "kaspresso", version.ref = "kaspresso" }
kaspresso-compose = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Firebase Libraries
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }

#MOCKITO
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" , version.ref="mockitoKotlin"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockkAgent" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
json = { module = "org.json:json", version.ref = "json" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
sonar = { id = "org.sonarqube", version.ref = "sonar" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
