[versions]
agp = "8.3.2"
coreTesting = "2.2.0"
kotlin = "1.8.10"
coreKtx = "1.13.1"
ktfmt = "0.17.0"
appcompat = "1.7.0"
material = "1.12.0"
composeBom = "2024.09.03"
composeActivity = "1.9.2"
composeViewModel = "2.8.6"
composeIconsExtended = "1.0.0"
lifecycleRuntimeKtx = "2.8.6"
json = "20240303"
mockitoAndroid = "5.13.0"
gms = "4.4.2"
mockkVersion = "1.13.7"
navigationCompose = "2.8.2"

# Google Service and Maps
playServicesAuth = "21.2.0"
playServicesMaps = "19.0.0"
mapsCompose = "4.3.3"
mapsComposeUtils = "4.3.0"

# Testing Unit
junit = "4.13.2"
mockitoCore = "5.13.0"
mockitoInline = "3.12.4"
mockitoKotlin = "5.4.0"
mockk = "1.13.7"


# Firebase Libraries
firebaseAuth = "23.0.0"
firebaseAuthKtx = "23.0.0"
firebaseDatabaseKtx = "21.0.0"
firebaseFirestore = "25.1.0"
firebaseUiAuth = "8.0.0"
firebaseCommonKtx = "21.0.0"

# Networking
okhttp = "4.12.0"


# Testing UI
espressoCore = "3.6.1"
junitVersion = "1.2.1"
kaspresso = "1.5.5"

mockkAgent = "1.13.7"
mockkAndroid = "1.13.7"
robolectric = "4.11.1"
sonar = "4.4.1.3373"
uiTestJunit4 = "1.7.3"
firebaseFunctionsKtx = "21.0.0"
runtimeLivedata = "1.7.4"
navigationTesting = "2.8.3"

# Documents
playServicesMlkitDocumentScanner = "16.0.0-beta1"
coil = "2.1.0"
bouquet = "1.1.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeIconsExtended" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
compose-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

kaspresso = { group = "com.kaspersky.android-components", name = "kaspresso", version.ref = "kaspresso" }
kaspresso-compose = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }

mockk-v1120 = { module = "io.mockk:mockk", version.ref = "mockkVersion" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Firebase Libraries
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebaseAuth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore", version.ref = "firebaseFirestore" }
firebase-ui-auth = { module = "com.firebaseui:firebase-ui-auth", version.ref = "firebaseUiAuth" }
firebase-common-ktx = { group = "com.google.firebase", name = "firebase-common-ktx", version.ref = "firebaseCommonKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseCommonKtx" }

#GOOGLE SERVICES & MAPS
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
maps-compose-utils = { module = "com.google.maps.android:maps-compose-utils", version.ref = "mapsComposeUtils" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

# Mockito
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockitoAndroid" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin" , version.ref="mockitoKotlin"}
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockkAgent" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockkAndroid" }
json = { module = "org.json:json", version.ref = "json" }

# Testing UI
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espressoCore" }

# Networking
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigationTesting" }

play-services-mlkit-document-scanner = { group = "com.google.android.gms", name = "play-services-mlkit-document-scanner", version.ref = "playServicesMlkitDocumentScanner" }
firebase-functions-ktx = { group = "com.google.firebase", name = "firebase-functions-ktx", version.ref = "firebaseFunctionsKtx" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
bouquet = { group = "io.github.grizzi91", name = "bouquet", version.ref = "bouquet" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
sonar = { id = "org.sonarqube", version.ref = "sonar" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }